# Generated by Django 3.2.5 on 2021-09-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HNC_posts', '0004_unvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='unvote',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unvote', to='HNC_posts.vote'),
        ),
    ]
